### ISSUE TITLE
Not able to use this on Angular version 5

### ISSUE THREAD

**Issue by sumeetqtech** [ngneat/cmdk#11]
## I'm submitting a...

<pre><code>
[ 
![Uploading Screen Shot 2023-12-28 at 4.25.26 PM.png…]()
] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by shhdharmen** [comment]
Angular 5 is way too old, please update.
